"""Synthetic task generation for SELPH curriculum.

Generates random well-typed programs, evaluates them on random inputs
to produce input/output examples, and wraps them as Specs.

Each stage has a vocabulary of available primitives and a depth budget.
Tasks are generated by sampling random compositions from the vocabulary,
then running them to extract example pairs.
"""

from __future__ import annotations
import random
from dataclasses import dataclass
from typing import Any
from .ast import Node, Symbol, Number, String, List, Spec, GoalExamples
from .eval import eval_node, apply_fn, standard_env, Env, Closure, BuiltinFn, EvalError
from .types import TNum, TStr, TBool, TFn, TList, Type
from .synthesize import Component


# ── Primitive definitions for each stage ─────────────────────────────

@dataclass
class Primitive:
    """A primitive operation available for task generation."""
    name: str
    type: TFn
    input_gen: Any = None  # callable() -> random input value


# String -> String primitives
STR_STR = [
    Primitive("string-upper", TFn((TStr(),), TStr())),
    Primitive("string-lower", TFn((TStr(),), TStr())),
    Primitive("string-reverse", TFn((TStr(),), TStr())),
    Primitive("string-trim", TFn((TStr(),), TStr())),
]

# String -> Number primitives
STR_NUM = [
    Primitive("string-length", TFn((TStr(),), TNum())),
]

# Number -> Number unary primitives
NUM_NUM_UNARY = [
    Primitive("abs", TFn((TNum(),), TNum())),
    Primitive("negate", TFn((TNum(),), TNum())),
    Primitive("even", TFn((TNum(),), TBool())),
]

# Number -> Number -> Number binary primitives
NUM_NUM_BINARY = [
    Primitive("add", TFn((TNum(), TNum()), TNum())),
    Primitive("subtract", TFn((TNum(), TNum()), TNum())),
    Primitive("multiply", TFn((TNum(), TNum()), TNum())),
    Primitive("min", TFn((TNum(), TNum()), TNum())),
    Primitive("max", TFn((TNum(), TNum()), TNum())),
]


# ── Input generators ─────────────────────────────────────────────────

def random_string(rng: random.Random, min_len: int = 1, max_len: int = 8) -> str:
    """Generate a random lowercase string."""
    length = rng.randint(min_len, max_len)
    return ''.join(rng.choice('abcdefghijklmnopqrstuvwxyz') for _ in range(length))


def random_padded_string(rng: random.Random) -> str:
    """Generate a string with whitespace padding."""
    s = random_string(rng, 1, 5)
    left = ' ' * rng.randint(1, 3)
    right = ' ' * rng.randint(1, 3)
    return left + s + right


def random_mixed_case(rng: random.Random) -> str:
    """Generate a mixed case string."""
    s = random_string(rng, 2, 6)
    return ''.join(c.upper() if rng.random() > 0.5 else c for c in s)


def random_number(rng: random.Random, lo: int = -10, hi: int = 10) -> float:
    return float(rng.randint(lo, hi))


def random_small_positive(rng: random.Random) -> float:
    return float(rng.randint(1, 20))


# ── Task generation ──────────────────────────────────────────────────

@dataclass
class GeneratedTask:
    """A synthetic task with its generating program."""
    name: str
    spec: Spec
    program_ast: Node      # the (lambda (x) ...) that solves it
    depth: int             # AST depth of the body
    primitives_used: list[str]


def _ast_value_to_node(val: Any) -> Node | None:
    """Convert a Python value to an AST literal for spec examples."""
    if isinstance(val, bool):
        return None  # skip bool outputs for now
    if isinstance(val, (int, float)):
        return Number(float(val))
    if isinstance(val, str):
        return String(val)
    return None


def generate_task_from_chain(chain: list[str], input_type: str,
                             inputs: list[Any], constants: dict[str, float] | None = None,
                             rng: random.Random | None = None,
                             name: str | None = None) -> GeneratedTask | None:
    """Generate a task from a chain of primitive operations.

    chain: list of primitive names to compose, e.g. ["string-trim", "string-upper"]
    input_type: "string" or "number"
    inputs: list of input values to generate examples from
    constants: for binary ops, maps op name to constant arg, e.g. {"add": 1.0}
    """
    if rng is None:
        rng = random.Random(42)
    if constants is None:
        constants = {}

    env = standard_env()

    # Build the AST: compose the chain right-to-left
    # chain[0] is applied first (innermost), chain[-1] last (outermost)
    # So (chain = [trim, upper]) means upper(trim(x))
    body: Node = Symbol("x")
    for op_name in chain:
        if op_name in constants:
            # Binary op with constant
            body = List((Symbol(op_name), body, Number(constants[op_name])))
        else:
            body = List((Symbol(op_name), body))

    fn_node = List((Symbol("lambda"), List((Symbol("x"),)), body))

    # Evaluate on inputs to get examples
    try:
        fn_val = eval_node(fn_node, env)
    except EvalError:
        return None

    pairs = []
    for inp in inputs:
        try:
            out = apply_fn(fn_val, [inp])
            in_node = _ast_value_to_node(inp)
            out_node = _ast_value_to_node(out)
            if in_node is not None and out_node is not None:
                pairs.append((in_node, out_node))
        except (EvalError, Exception):
            continue

    if len(pairs) < 2:
        return None

    # Determine output type
    sample_out = pairs[0][1]
    out_type = "number" if isinstance(sample_out, Number) else "string"

    spec = Spec(
        type_expr=Symbol(out_type),
        goal=GoalExamples(pairs=tuple(pairs)),
    )

    if name is None:
        name = "_".join(chain)
        if constants:
            name += "_" + "_".join(f"{k}{int(v)}" for k, v in constants.items())

    return GeneratedTask(
        name=name,
        spec=spec,
        program_ast=fn_node,
        depth=len(chain),
        primitives_used=chain,
    )


# ── Stage-specific task generators ───────────────────────────────────

def generate_stage0_tasks(n: int = 20, seed: int = 42) -> list[GeneratedTask]:
    """Generate Stage 0 tasks: single primitive applications."""
    rng = random.Random(seed)
    tasks = []

    # String -> String (single ops)
    for prim in STR_STR:
        if prim.name == "string-trim":
            inputs = [random_padded_string(rng) for _ in range(5)]
        elif prim.name in ("string-upper", "string-lower"):
            inputs = [random_mixed_case(rng) for _ in range(5)]
        else:
            inputs = [random_string(rng) for _ in range(5)]

        task = generate_task_from_chain([prim.name], "string", inputs, rng=rng)
        if task:
            tasks.append(task)

    # String -> Number
    for prim in STR_NUM:
        inputs = [random_string(rng) for _ in range(5)]
        task = generate_task_from_chain([prim.name], "string", inputs, rng=rng)
        if task:
            tasks.append(task)

    # Number -> Number (unary)
    for prim in NUM_NUM_UNARY:
        if prim.name == "even":
            continue  # bool output, skip
        inputs = [random_number(rng) for _ in range(5)]
        task = generate_task_from_chain([prim.name], "number", inputs, rng=rng)
        if task:
            tasks.append(task)

    # Number -> Number (binary with constant)
    for prim in NUM_NUM_BINARY:
        for const in [1.0, 2.0, -1.0]:
            inputs = [random_number(rng) for _ in range(5)]
            task = generate_task_from_chain(
                [prim.name], "number", inputs,
                constants={prim.name: const}, rng=rng,
                name=f"{prim.name}_{int(const)}",
            )
            if task:
                tasks.append(task)
                if len(tasks) >= n:
                    return tasks

    return tasks[:n]


def generate_stage1_tasks(n: int = 30, seed: int = 43) -> list[GeneratedTask]:
    """Generate Stage 1 tasks: two-step compositions."""
    rng = random.Random(seed)
    tasks = []

    # String -> String -> String (compose two str ops)
    str_ops = ["string-upper", "string-lower", "string-reverse", "string-trim"]
    for op1 in str_ops:
        for op2 in str_ops:
            if op1 == op2:
                continue
            if op1 == "string-trim":
                inputs = [random_padded_string(rng) for _ in range(5)]
            else:
                inputs = [random_mixed_case(rng) for _ in range(5)]

            task = generate_task_from_chain([op1, op2], "string", inputs, rng=rng)
            if task:
                tasks.append(task)
                if len(tasks) >= n:
                    return tasks

    # String -> Number -> Number (str op then num op)
    for num_op in ["add", "multiply"]:
        for const in [1.0, 2.0]:
            inputs = [random_string(rng, 1, 6) for _ in range(5)]
            task = generate_task_from_chain(
                ["string-length", num_op], "string", inputs,
                constants={num_op: const}, rng=rng,
            )
            if task:
                tasks.append(task)

    # Number -> Number -> Number (two num ops)
    for op1 in ["abs", "negate"]:
        for op2_name in ["add", "subtract"]:
            for const in [1.0]:
                inputs = [random_number(rng) for _ in range(5)]
                task = generate_task_from_chain(
                    [op1, op2_name], "number", inputs,
                    constants={op2_name: const}, rng=rng,
                )
                if task:
                    tasks.append(task)

    return tasks[:n]


def generate_stage2_tasks(n: int = 20, seed: int = 44) -> list[GeneratedTask]:
    """Generate Stage 2 tasks: three-step compositions."""
    rng = random.Random(seed)
    tasks = []

    # String -> String -> String -> String (three str ops)
    str_ops = ["string-upper", "string-lower", "string-reverse", "string-trim"]
    tried = set()
    for op1 in str_ops:
        for op2 in str_ops:
            for op3 in str_ops:
                if len({op1, op2, op3}) < 2:
                    continue  # skip all-same
                key = (op1, op2, op3)
                if key in tried:
                    continue
                tried.add(key)

                if op1 == "string-trim":
                    inputs = [random_padded_string(rng) for _ in range(5)]
                else:
                    inputs = [random_mixed_case(rng) for _ in range(5)]

                task = generate_task_from_chain([op1, op2, op3], "string", inputs, rng=rng)
                if task:
                    tasks.append(task)
                    if len(tasks) >= n:
                        return tasks

    # String -> String -> Number (two str ops then length)
    for op1 in str_ops:
        for op2 in ["string-length"]:
            if op1 == "string-trim":
                inputs = [random_padded_string(rng) for _ in range(5)]
            else:
                inputs = [random_mixed_case(rng) for _ in range(5)]

            task = generate_task_from_chain([op1, op2], "string", inputs, rng=rng)
            if task:
                tasks.append(task)

    return tasks[:n]


def generate_stage3_tasks(n: int = 15, seed: int = 45) -> list[GeneratedTask]:
    """Generate Stage 3 tasks: four-step compositions."""
    rng = random.Random(seed)
    tasks = []

    str_ops = ["string-upper", "string-lower", "string-reverse", "string-trim"]
    tried = set()
    for op1 in str_ops:
        for op2 in str_ops:
            for op3 in str_ops:
                for op4 in str_ops:
                    if len({op1, op2, op3, op4}) < 2:
                        continue
                    key = (op1, op2, op3, op4)
                    if key in tried:
                        continue
                    tried.add(key)

                    if op1 == "string-trim":
                        inputs = [random_padded_string(rng) for _ in range(5)]
                    else:
                        inputs = [random_mixed_case(rng) for _ in range(5)]

                    task = generate_task_from_chain(
                        [op1, op2, op3, op4], "string", inputs, rng=rng)
                    if task:
                        tasks.append(task)
                        if len(tasks) >= n:
                            return tasks

    return tasks[:n]


# ── Stages 4-7: New operation classes ────────────────────────────────

def generate_stage4_tasks(n: int = 20, seed: int = 46) -> list[GeneratedTask]:
    """Stage 4: Branching (if/then/else).

    Tasks require different behavior for different input ranges.
    """
    rng = random.Random(seed)
    tasks = []
    env = standard_env()

    # Threshold functions
    defs = [
        ("thresh_pos", lambda x: 1.0 if x > 0 else 0.0,
         [float(i) for i in range(-5, 6)]),
        ("thresh_neg", lambda x: 1.0 if x < 0 else 0.0,
         [float(i) for i in range(-5, 6)]),
        ("thresh_5", lambda x: 1.0 if x > 5 else 0.0,
         [float(i) for i in range(0, 11)]),
        ("abs_manual", lambda x: -x if x < 0 else x,
         [float(i) for i in range(-5, 6)]),
        ("relu", lambda x: x if x > 0 else 0.0,
         [float(i) for i in range(-5, 6)]),
        ("abs_double", lambda x: -x if x < 0 else x * 2,
         [float(i) for i in range(-5, 6)]),
        ("negate_or_add1", lambda x: -x if x < 0 else x + 1,
         [float(i) for i in range(-5, 6)]),
        ("double_if_even", lambda x: x * 2 if x % 2 == 0 else x,
         [float(i) for i in range(0, 10)]),
        ("negate_if_odd", lambda x: -x if x % 2 != 0 else x,
         [float(i) for i in range(0, 10)]),
    ]

    for name, fn, inputs in defs:
        pairs = [(Number(x), Number(fn(x))) for x in inputs]
        spec = Spec(type_expr=Symbol("number"), goal=GoalExamples(pairs=tuple(pairs)))
        tasks.append(GeneratedTask(
            name=name, spec=spec,
            program_ast=List((Symbol("lambda"), List((Symbol("x"),)), Symbol("?"))),
            depth=2, primitives_used=["if"],
        ))

    return tasks[:n]


def generate_stage5_tasks(n: int = 15, seed: int = 47) -> list[GeneratedTask]:
    """Stage 5: Composition of branching + arithmetic chains."""
    rng = random.Random(seed)
    tasks = []

    defs = [
        ("abs_then_double", lambda x: abs(x) * 2,
         [float(i) for i in range(-5, 6)]),
        ("relu_then_add1", lambda x: (x if x > 0 else 0.0) + 1.0,
         [float(i) for i in range(-5, 6)]),
        ("negate_abs", lambda x: -abs(x),
         [float(i) for i in range(-5, 6)]),
        ("abs_mod3", lambda x: abs(x) % 3,
         [float(i) for i in range(-10, 11)]),
        ("classify_3way", lambda x: 0.0 if x < 0 else (1.0 if x < 10 else 2.0),
         [float(i) for i in range(-5, 15)]),
    ]

    for name, fn, inputs in defs:
        pairs = [(Number(x), Number(float(fn(x)))) for x in inputs]
        spec = Spec(type_expr=Symbol("number"), goal=GoalExamples(pairs=tuple(pairs)))
        tasks.append(GeneratedTask(
            name=name, spec=spec,
            program_ast=List((Symbol("lambda"), List((Symbol("x"),)), Symbol("?"))),
            depth=3, primitives_used=["if", "abs"],
        ))

    return tasks[:n]
