#!/usr/bin/env python3
"""GRPO (Group Relative Policy Optimization) for the query channel.

Trains the iterative refinement model to discover when and what to query
via outcome-based RL. Teacher-forced query training adds only +0.3pp;
GRPO lets the model learn query strategies from trajectory rewards.

Usage:
    python3 -m neural_selph.iterative.grpo_mlx --epochs 50 --dim 96 --feat-dim 48 --num-layers 3
"""
from __future__ import annotations

import argparse
import copy
import json
import math
import os
import random
import sys
import time
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path

PG_ROOT = Path(os.environ.get("PG_ROOT", os.path.expanduser("~/projects/parameter-golf")))
sys.path.insert(0, str(PG_ROOT))

import mlx.core as mx
import mlx.nn as nn
import mlx.optimizers as optim
from mlx.utils import tree_flatten, tree_unflatten

from ssm_bin_es.experiment.model import MultiScaleFFNLM

from neural_selph.iterative.sexpr_tokenizer import SexprTokenizer, build_default_tokenizer
from neural_selph.iterative.train_mlx import build_model
from neural_selph.iterative.generate_traces import evaluate_in_kb, parse_sexpr, extract_expr, extract_question_context
from neural_selph.iterative.eval_mlx import build_input, extract_edit_from_gen, iterative_refine

DATA_DIR = Path(__file__).parent.parent / "data"


# ============================================================================
# Data structures
# ============================================================================

@dataclass
class StepData:
    """One refinement step's generation data."""
    context_ids: list[int]    # input context (not generated by model)
    gen_ids: list[int]        # all tokens after context (model + injected)
    gen_mask: list[bool]      # True = model-generated, False = injected
    old_log_probs: list[float]  # log-prob at generation time (model-generated only)


@dataclass
class Trajectory:
    """A full multi-step refinement trajectory."""
    task_idx: int
    correct: bool
    num_steps: int
    reward: float
    steps: list[StepData] = field(default_factory=list)
    used_query: bool = False


# ============================================================================
# Trajectory collection
# ============================================================================

def generate_with_log_probs(
    model: MultiScaleFFNLM,
    input_ids: mx.array,
    tokenizer: SexprTokenizer,
    kb: dict,
    temperature: float = 0.7,
    max_new_tokens: int = 60,
    max_queries: int = 3,
) -> tuple[list[int], list[bool], list[float], bool]:
    """Autoregressive generation with sampling, log-prob collection, and query support.

    Returns:
        gen_ids: all generated/injected token IDs
        gen_mask: True for model-generated tokens, False for injected
        log_probs: log-prob for each model-generated token (len = sum(gen_mask))
        used_query: whether any <query> was emitted
    """
    ids = input_ids[None, :]  # (1, seq_len)
    gen_ids = []
    gen_mask = []
    log_probs = []
    used_query = False

    query_start_id = tokenizer.token_to_id.get("<query>")
    query_end_id = tokenizer.token_to_id.get("</query>")

    for _ in range(max_new_tokens):
        x = model(ids)
        logits = x[:, -1, :] @ model.tok_emb.weight.astype(x.dtype).T
        logits = model.softcap(logits).astype(mx.float32)

        # Sample
        probs = mx.softmax(logits / temperature, axis=-1)
        log_p = mx.log(probs + 1e-10)
        next_id = int(mx.random.categorical(log_p).item())
        token_log_prob = float(log_p[0, next_id].item())
        mx.eval(log_p)
        del x, logits, probs

        gen_ids.append(next_id)
        gen_mask.append(True)
        log_probs.append(token_log_prob)

        if next_id == tokenizer.eos_id:
            break

        ids = mx.concatenate([ids, mx.array([[next_id]], dtype=mx.int32)], axis=1)

        # Query interception
        if next_id == query_start_id and max_queries > 0:
            used_query = True
            query_token_ids = []
            for _ in range(20):
                x = model(ids)
                logits = x[:, -1, :] @ model.tok_emb.weight.astype(x.dtype).T
                logits = model.softcap(logits).astype(mx.float32)
                probs = mx.softmax(logits / temperature, axis=-1)
                log_p = mx.log(probs + 1e-10)
                qid = int(mx.random.categorical(log_p).item())
                q_log_prob = float(log_p[0, qid].item())
                mx.eval(log_p)
                del x, logits, probs

                gen_ids.append(qid)
                gen_mask.append(True)  # query body is model-generated
                log_probs.append(q_log_prob)

                ids = mx.concatenate([ids, mx.array([[qid]], dtype=mx.int32)], axis=1)

                if qid == query_end_id:
                    break
                query_token_ids.append(qid)

            # Evaluate query against KB
            query_sexpr = tokenizer.decode_to_sexpr(query_token_ids)
            q_result = ""
            if query_sexpr and "_HOLE_" not in query_sexpr:
                tree = parse_sexpr(query_sexpr)
                result = evaluate_in_kb(tree, kb)
                if result is not None:
                    q_result = str(result)

            # Inject <q_out> result </q_out> — NOT model-generated
            result_tokens = ["<q_out>"]
            if q_result:
                try:
                    float(q_result)
                    result_tokens.extend(tokenizer.tokenize_number(q_result))
                except ValueError:
                    if q_result in tokenizer.token_to_id:
                        result_tokens.append(q_result)
            result_tokens.append("</q_out>")

            result_ids = [tokenizer.token_to_id[t] for t in result_tokens
                          if t in tokenizer.token_to_id]
            for rid in result_ids:
                gen_ids.append(rid)
                gen_mask.append(False)  # injected, not model-generated
            ids = mx.concatenate([ids, mx.array([result_ids], dtype=mx.int32)], axis=1)
            max_queries -= 1

    return gen_ids, gen_mask, log_probs, used_query


def collect_trajectory(
    model: MultiScaleFFNLM,
    tokenizer: SexprTokenizer,
    kb: dict,
    task: dict,
    temperature: float = 0.7,
    max_steps: int = 5,
) -> Trajectory:
    """Run one sampled iterative refinement trajectory, collecting log-probs."""
    expr_str = extract_expr(task["completion"])
    q_type, entities = extract_question_context(task["prompt"], expr_str)
    expected = task["answer"]

    current_expr = "_HOLE_"
    traj = Trajectory(task_idx=0, correct=False, num_steps=0, reward=0.0)

    for step in range(max_steps):
        # Determine feedback
        if current_expr == "_HOLE_" or "_HOLE_" in current_expr:
            feedback_type = "INCOMPLETE"
            feedback_value = ""
        else:
            tree = parse_sexpr(current_expr)
            result = evaluate_in_kb(tree, kb)
            if result is None:
                feedback_type = "ERROR"
                feedback_value = ""
            elif str(result) == str(expected):
                traj.correct = True
                traj.num_steps = step
                traj.reward = compute_reward(True, step)
                return traj
            else:
                feedback_type = "WRONG"
                feedback_value = str(result)

        # Build input
        input_ids = build_input(tokenizer, current_expr, feedback_type,
                                feedback_value, q_type, entities)
        context_ids = input_ids.tolist()

        # Generate with sampling + log-prob collection
        gen_ids, gen_mask, log_probs, used_q = generate_with_log_probs(
            model, input_ids, tokenizer, kb, temperature=temperature)

        if used_q:
            traj.used_query = True

        traj.steps.append(StepData(
            context_ids=context_ids,
            gen_ids=gen_ids,
            gen_mask=gen_mask,
            old_log_probs=log_probs,
        ))

        # Extract edit
        gen_tokens = tokenizer.decode(gen_ids)
        if "NO_OP" in gen_tokens:
            if current_expr != "_HOLE_" and "_HOLE_" not in current_expr:
                tree = parse_sexpr(current_expr)
                result = evaluate_in_kb(tree, kb)
                traj.correct = result is not None and str(result) == str(expected)
            traj.num_steps = step + 1
            traj.reward = compute_reward(traj.correct, traj.num_steps)
            return traj

        new_expr = extract_edit_from_gen(gen_ids, tokenizer)
        if new_expr and new_expr != current_expr:
            current_expr = new_expr

    # Final check
    if current_expr != "_HOLE_" and "_HOLE_" not in current_expr:
        tree = parse_sexpr(current_expr)
        result = evaluate_in_kb(tree, kb)
        traj.correct = result is not None and str(result) == str(expected)

    traj.num_steps = max_steps
    traj.reward = compute_reward(traj.correct, max_steps)
    return traj


def compute_reward(correct: bool, num_steps: int) -> float:
    if not correct:
        return 0.0
    return 1.0 - 0.05 * max(0, num_steps - 1)


# ============================================================================
# Log-prob computation
# ============================================================================

def compute_step_log_probs(
    model: MultiScaleFFNLM,
    step: StepData,
) -> mx.array:
    """Recompute log-probs for model-generated tokens in a step.

    Single forward pass on [context + gen], extract log-probs at gen positions.
    Returns log-probs only for tokens where gen_mask is True.
    """
    full_ids = step.context_ids + step.gen_ids
    input_ids = mx.array([full_ids[:-1]], dtype=mx.int32)  # shift right

    x = model(input_ids)  # (1, seq_len, dim)
    logits = x @ model.tok_emb.weight.astype(x.dtype).T
    logits = model.softcap(logits).astype(mx.float32)
    log_probs_all = logits - mx.logsumexp(logits, axis=-1, keepdims=True)  # (1, seq_len, vocab)

    # Extract log-probs at generation positions
    ctx_len = len(step.context_ids)
    result = []
    lp_idx = 0
    for i, (gid, is_model) in enumerate(zip(step.gen_ids, step.gen_mask)):
        if is_model:
            pos = ctx_len + i - 1  # position in input that predicts this token
            lp = log_probs_all[0, pos, gid]
            result.append(lp)

    if not result:
        return mx.array([], dtype=mx.float32)
    return mx.stack(result)


# ============================================================================
# GRPO loss
# ============================================================================

def grpo_loss(
    model: MultiScaleFFNLM,
    ref_model: MultiScaleFFNLM,
    trajectories: list[Trajectory],
    advantages: list[float],
    clip_eps: float = 0.2,
    kl_coef: float = 0.05,
) -> mx.array:
    """Compute GRPO loss over a batch of trajectories.

    For each trajectory's model-generated tokens:
      ratio = exp(new_log_prob - old_log_prob)
      clipped_ratio = clip(ratio, 1-eps, 1+eps)
      pg_loss = -min(ratio * A, clipped_ratio * A)
      kl_penalty = kl_coef * (new_log_prob - ref_log_prob)
    """
    total_loss = mx.array(0.0)
    total_tokens = 0

    for traj, advantage in zip(trajectories, advantages):
        if abs(advantage) < 1e-8:
            continue  # skip zero-advantage trajectories

        for step in traj.steps:
            model_gen_count = sum(step.gen_mask)
            if model_gen_count == 0:
                continue

            # Recompute log-probs under current policy
            new_lp = compute_step_log_probs(model, step)
            ref_lp = compute_step_log_probs(ref_model, step)
            old_lp = mx.array(step.old_log_probs, dtype=mx.float32)

            if new_lp.size == 0:
                continue

            # PPO clipped objective
            ratio = mx.exp(new_lp - old_lp)
            adv = mx.array(advantage, dtype=mx.float32)
            surr1 = ratio * adv
            surr2 = mx.clip(ratio, 1.0 - clip_eps, 1.0 + clip_eps) * adv
            pg_loss = -mx.minimum(surr1, surr2)

            # KL penalty against reference
            kl = new_lp - ref_lp
            step_loss = mx.sum(pg_loss + kl_coef * kl)

            total_loss = total_loss + step_loss
            total_tokens += int(new_lp.size)

    if total_tokens == 0:
        return mx.array(0.0)
    return total_loss / total_tokens


# ============================================================================
# Evaluation
# ============================================================================

def quick_eval(
    model: MultiScaleFFNLM,
    tokenizer: SexprTokenizer,
    kb: dict,
    eval_tasks: list[dict],
    max_steps: int = 5,
    use_queries: bool = True,
) -> dict:
    """Quick eval on a subset, returns accuracy by depth."""
    results = defaultdict(lambda: {"ok": 0, "total": 0, "queries": 0})

    for task in eval_tasks:
        depth = task["depth"]
        answer = task["answer"]
        expr_str = extract_expr(task["completion"])
        q_type, entities = extract_question_context(task["prompt"], expr_str)

        if use_queries:
            # Use greedy generation with queries
            from neural_selph.iterative.eval_mlx import generate_with_queries as gen_q
            _, _, ok = iterative_refine(
                model, tokenizer, answer, kb, q_type, entities,
                max_steps=max_steps, use_queries=True)
        else:
            _, _, ok = iterative_refine(
                model, tokenizer, answer, kb, q_type, entities,
                max_steps=max_steps, use_queries=False)

        results[depth]["total"] += 1
        if ok:
            results[depth]["ok"] += 1

    return dict(results)


# ============================================================================
# Training
# ============================================================================

def train_grpo(args):
    print(f"MLX backend on {mx.default_device()}")

    tokenizer = build_default_tokenizer()
    kb = json.loads((DATA_DIR / "geo_kb.json").read_text())
    data = json.loads((DATA_DIR / "geo_train.json").read_text())
    print(f"Tasks: {len(data)}, Vocab: {tokenizer.vocab_size}")

    # Train/eval split
    random.seed(42)
    indices = list(range(len(data)))
    random.shuffle(indices)
    split = int(0.9 * len(indices))
    train_tasks = [data[i] for i in indices[:split]]
    eval_tasks = [data[i] for i in indices[split:]]
    # Subsample eval for speed
    eval_subset = eval_tasks[:min(100, len(eval_tasks))]

    # Build policy model and load SFT weights
    model = build_model(tokenizer.vocab_size, args)
    sft_path = args.sft_path
    weights = dict(mx.load(sft_path))
    model.load_weights(list(weights.items()))
    mx.eval(model.parameters())

    n_params = sum(p.size for _, p in tree_flatten(model.parameters()))
    print(f"Policy model: {n_params:,} params, loaded from {sft_path}")

    # Build frozen reference model
    ref_model = build_model(tokenizer.vocab_size, args)
    ref_model.load_weights(list(weights.items()))
    mx.eval(ref_model.parameters())
    ref_model.eval()  # always in eval mode

    # Optimizer
    optimizer = optim.Adam(learning_rate=args.lr)

    # Baseline eval
    print("\n--- SFT Baseline (no queries) ---")
    baseline = quick_eval(model, tokenizer, kb, eval_subset, use_queries=False)
    total_ok = sum(v["ok"] for v in baseline.values())
    total_n = sum(v["total"] for v in baseline.values())
    print(f"  Overall: {total_ok}/{total_n} ({total_ok/max(total_n,1)*100:.1f}%)")
    for d in sorted(baseline):
        r = baseline[d]
        print(f"  Depth {d}: {r['ok']}/{r['total']} ({r['ok']/max(r['total'],1)*100:.1f}%)")

    # GRPO training loop
    print(f"\n--- GRPO Training ---")
    print(f"  group_size={args.group_size}, temperature={args.temperature}")
    print(f"  clip_eps={args.clip_eps}, kl_coef={args.kl_coef}, lr={args.lr}")
    print(f"  batch_size={args.batch_size}, epochs={args.epochs}")

    best_acc = total_ok / max(total_n, 1)
    t0 = time.time()

    for epoch in range(args.epochs):
        model.train()
        epoch_loss = 0.0
        epoch_batches = 0
        epoch_trajs = 0
        epoch_correct = 0
        epoch_queries = 0

        # Shuffle tasks each epoch
        random.shuffle(train_tasks)

        for batch_start in range(0, min(len(train_tasks), args.tasks_per_epoch), args.batch_size):
            batch_end = min(batch_start + args.batch_size, len(train_tasks))
            batch_tasks = train_tasks[batch_start:batch_end]

            # Phase 1: Collect trajectories (no grad)
            model.eval()
            all_trajectories = []
            all_advantages = []

            for task in batch_tasks:
                group_trajs = []
                for g in range(args.group_size):
                    traj = collect_trajectory(
                        model, tokenizer, kb, task,
                        temperature=args.temperature,
                        max_steps=args.max_steps,
                    )
                    traj.task_idx = id(task)
                    group_trajs.append(traj)
                    epoch_trajs += 1
                    if traj.correct:
                        epoch_correct += 1
                    if traj.used_query:
                        epoch_queries += 1

                # Group-normalize advantages
                rewards = [t.reward for t in group_trajs]
                mean_r = sum(rewards) / len(rewards)
                std_r = math.sqrt(sum((r - mean_r) ** 2 for r in rewards) / len(rewards))
                if std_r < 1e-8:
                    # All same reward — zero advantage
                    advs = [0.0] * len(rewards)
                else:
                    advs = [(r - mean_r) / (std_r + 1e-8) for r in rewards]

                all_trajectories.extend(group_trajs)
                all_advantages.extend(advs)

            # Skip if no meaningful advantages
            if all(abs(a) < 1e-8 for a in all_advantages):
                continue

            # Phase 2: Compute GRPO loss and update
            model.train()
            loss_fn = lambda m: grpo_loss(
                m, ref_model, all_trajectories, all_advantages,
                clip_eps=args.clip_eps, kl_coef=args.kl_coef,
            )
            loss, grads = nn.value_and_grad(model, loss_fn)(model)
            grads, _ = optim.clip_grad_norm(grads, max_norm=1.0)
            optimizer.update(model, grads)
            mx.eval(model.parameters(), optimizer.state, loss)

            batch_loss = float(loss.item())
            if not math.isnan(batch_loss):
                epoch_loss += batch_loss
                epoch_batches += 1

        # Epoch summary
        avg_loss = epoch_loss / max(epoch_batches, 1)
        traj_acc = epoch_correct / max(epoch_trajs, 1)
        elapsed = time.time() - t0

        # Eval periodically
        if (epoch + 1) % args.eval_every == 0 or epoch == args.epochs - 1:
            model.eval()
            # Eval with queries
            res_q = quick_eval(model, tokenizer, kb, eval_subset, use_queries=True)
            ok_q = sum(v["ok"] for v in res_q.values())
            n_q = sum(v["total"] for v in res_q.values())
            acc_q = ok_q / max(n_q, 1)

            # Eval without queries
            res_nq = quick_eval(model, tokenizer, kb, eval_subset, use_queries=False)
            ok_nq = sum(v["ok"] for v in res_nq.values())
            acc_nq = ok_nq / max(n_q, 1)

            marker = ""
            if acc_q > best_acc:
                best_acc = acc_q
                save_path = DATA_DIR / "iterative_model_grpo.npz"
                flat = dict(tree_flatten(model.parameters()))
                mx.savez(str(save_path), **flat)
                marker = " *saved*"

            print(f"epoch {epoch+1:3d}/{args.epochs}  loss={avg_loss:.4f}  "
                  f"traj_acc={traj_acc:.2f}  queries={epoch_queries}/{epoch_trajs}  "
                  f"eval_q={ok_q}/{n_q}({acc_q*100:.1f}%)  "
                  f"eval_nq={ok_nq}/{n_q}({acc_nq*100:.1f}%)  "
                  f"elapsed={elapsed:.0f}s{marker}")

            # Per-depth breakdown
            for d in sorted(res_q):
                rq = res_q[d]
                rnq = res_nq.get(d, {"ok": 0, "total": 0})
                print(f"  d={d}: q={rq['ok']}/{rq['total']}  nq={rnq['ok']}/{rnq['total']}")
        else:
            print(f"epoch {epoch+1:3d}/{args.epochs}  loss={avg_loss:.4f}  "
                  f"traj_acc={traj_acc:.2f}  queries={epoch_queries}/{epoch_trajs}  "
                  f"elapsed={elapsed:.0f}s")

    print(f"\nBest eval accuracy (with queries): {best_acc*100:.1f}%")
    print(f"Total time: {time.time() - t0:.0f}s")


def main():
    parser = argparse.ArgumentParser(description="GRPO training for query channel")
    # Model architecture (must match SFT checkpoint)
    parser.add_argument("--dim", type=int, default=96)
    parser.add_argument("--feat-dim", type=int, default=48)
    parser.add_argument("--state-dim", type=int, default=8)
    parser.add_argument("--num-layers", type=int, default=3)
    parser.add_argument("--num-scales", type=int, default=3)
    parser.add_argument("--shifts", type=int, nargs="+", default=[0, 1, 2, 4])
    parser.add_argument("--a-log-mults", type=float, nargs="+", default=[2.0, 1.0, 0.3])
    parser.add_argument("--mlp-mult", type=int, default=2)
    parser.add_argument("--weight-tie-layers", type=int, default=0)
    # GRPO hyperparameters
    parser.add_argument("--sft-path", default=str(DATA_DIR / "iterative_model_mlx.npz"))
    parser.add_argument("--group-size", type=int, default=4)
    parser.add_argument("--temperature", type=float, default=0.7)
    parser.add_argument("--clip-eps", type=float, default=0.2)
    parser.add_argument("--kl-coef", type=float, default=0.05)
    parser.add_argument("--lr", type=float, default=1e-5)
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument("--tasks-per-epoch", type=int, default=256)
    parser.add_argument("--epochs", type=int, default=50)
    parser.add_argument("--max-steps", type=int, default=5)
    parser.add_argument("--eval-every", type=int, default=5)
    args = parser.parse_args()
    train_grpo(args)


if __name__ == "__main__":
    main()
